algo_name: DQN-CNN-Space
env: SpaceInvaders-ram-v0
max_ep: 2000
batch_size: 128
replay_buffer_size: 1e6
exploration: 1000 
model_save_path: ../model/cnn/space/
rb_save_path: ../rb/cnn/space/
save_interval: 200
model_params:
  lr: 1e-5
  epsilon: .01
  gamma: .99